#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app:
    resource: '../src/Controller/'
    type: annotation

calendar_events:
    path: /calendar/events
    controller: App\Controller\EvenementController::calendarEvents    

